## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.12.1+cu113


In [2]:
!nvidia-smi

Sat Oct  8 18:19:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors

### Creating

PyTorch tensors are created using `torch.tensor()`

https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[
    [1, 2, 3],
    [3, 6, 9],
    [2, 4, 5]
]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random number and then adjust those random numbers to better represent the data.

`Strart with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6472, 0.4026, 0.2191, 0.6139],
        [0.4728, 0.4460, 0.5593, 0.7703],
        [0.9038, 0.3362, 0.0245, 0.6395]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channels (R, G, B), height, widht
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [20]:
torch.rand(3, 3)

tensor([[0.0976, 0.3335, 0.9118],
        [0.2731, 0.7084, 0.2145],
        [0.6156, 0.4236, 0.0163]])

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype # default datatype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range()
torch.range(0, 10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
torch.__version__

'1.12.1+cu113'

In [27]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
step_range = torch.arange(start=0, end=10, step=2)
step_range

tensor([0, 2, 4, 6, 8])

In [29]:
# Creating tensors like
one_to_ten = torch.arange(start=1, end=11, step=1)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note** Tensor datatypes is one of the 3 big errors you will run into with PyTorch & deep learning:


1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)



In [30]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], 
    dtype=None, # what datatype is the tensor(e.g. float32 or float16)
    device=None, # what device is your tensor on  ("cuda")
    requires_grad=False # whether or not to track gradients with this tensors operations
)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [37]:
long_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
long_tensor, long_tensor.dtype

(tensor([3, 6, 9]), torch.int64)

In [38]:
long_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1.   Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2.   Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3.   Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4430, 0.7810, 0.6529, 0.8104],
        [0.6485, 0.7129, 0.6298, 0.0539],
        [0.8392, 0.9426, 0.9160, 0.5171]])

In [40]:
some_tensor.size()

torch.Size([3, 4])

In [41]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4430, 0.7810, 0.6529, 0.8104],
        [0.6485, 0.7129, 0.6298, 0.0539],
        [0.8392, 0.9426, 0.9160, 0.5171]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [42]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [43]:
tensor * 10

tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
tensor - 10

tensor([-9, -8, -7])

In [46]:
# PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

[More information on multiplying matrices](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

[matrixmultiplication.xyz](http://matrixmultiplication.xyz)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2 ) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [50]:
#torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

In [51]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.5457, 0.0729, 0.5209],
        [0.4236, 0.0615, 0.4143],
        [0.5609, 0.0778, 0.5411]])

In [52]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [53]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [54]:
# Matrix multiplication by hand
(1 * 1) + (2 * 2) + (3 * 3)

14

In [55]:
tensor @ tensor

tensor(14)

In [56]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value) # ten times slower than torch.matmul()

tensor(14)
CPU times: user 385 µs, sys: 0 ns, total: 385 µs
Wall time: 393 µs


In [57]:
%%time
torch.matmul(tensor, tensor) # µs (microseconds)

CPU times: user 30 µs, sys: 4 µs, total: 34 µs
Wall time: 37.4 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [59]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

In [60]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [61]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [62]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [63]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape }")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [64]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [66]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [68]:
#torch.mean(x)

In [69]:
x.dtype

torch.int64

In [70]:
# The torch.mean() requies a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [71]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [72]:
position_of_min_val = x.argmin()
position_of_min_val

tensor(0)

In [73]:
position_of_max_val = x.argmax()
position_of_max_val

tensor(9)

In [74]:
x[position_of_max_val]

tensor(90)

## Reshaping, stacking, squeezing and usqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the origina tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Sqeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [75]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [77]:
# Add an extra dimension
#x_reshaped = x.reshape(1, 7)

In [78]:
# The original tensor has 10 element!!!
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [79]:
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]), torch.Size([10, 1]))

In [80]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]), torch.Size([5, 2]))

In [81]:
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [82]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [83]:
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [84]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x # x also changed!!!

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [85]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [86]:
x_stacked_v = torch.stack([x, x, x, x], dim=1)
x_stacked_v

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [87]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshape
x_sqeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_sqeezed}")
print(f"New shape: {x_sqeezed.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [88]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_sqeezed}")
print(f"Previous shape: {x_sqeezed.shape}")

# Add an extra dimension with unsqueeze()
x_unsqueezed = x_sqeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [89]:
x_unsqueezed_v = x_sqeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed_v}")
print(f"New shape: {x_unsqueezed_v.shape}")


New tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [90]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
x_original, x_original.shape

(tensor([[[0.2612, 0.5813, 0.6433],
          [0.2086, 0.4309, 0.0986],
          [0.4746, 0.3536, 0.3842],
          ...,
          [0.3385, 0.5249, 0.4020],
          [0.5975, 0.2415, 0.1697],
          [0.0919, 0.3704, 0.9137]],
 
         [[0.8731, 0.4365, 0.7781],
          [0.8030, 0.2039, 0.4081],
          [0.4243, 0.7007, 0.5327],
          ...,
          [0.6451, 0.3696, 0.5408],
          [0.6959, 0.6232, 0.7002],
          [0.3013, 0.0524, 0.1694]],
 
         [[0.5947, 0.6360, 0.6582],
          [0.6101, 0.1025, 0.6622],
          [0.8823, 0.9094, 0.7871],
          ...,
          [0.4136, 0.6889, 0.7939],
          [0.8682, 0.5269, 0.4366],
          [0.3156, 0.7484, 0.5521]],
 
         ...,
 
         [[0.7689, 0.1866, 0.7134],
          [0.3695, 0.8539, 0.3168],
          [0.8949, 0.2419, 0.5800],
          ...,
          [0.8981, 0.9267, 0.2466],
          [0.1653, 0.4852, 0.8366],
          [0.0364, 0.6821, 0.7805]],
 
         [[0.4602, 0.7672, 0.2792],
          [0

In [91]:
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # [colour channel, height, width]
x_permuted, x_permuted.shape

(tensor([[[0.2612, 0.2086, 0.4746,  ..., 0.3385, 0.5975, 0.0919],
          [0.8731, 0.8030, 0.4243,  ..., 0.6451, 0.6959, 0.3013],
          [0.5947, 0.6101, 0.8823,  ..., 0.4136, 0.8682, 0.3156],
          ...,
          [0.7689, 0.3695, 0.8949,  ..., 0.8981, 0.1653, 0.0364],
          [0.4602, 0.4883, 0.3874,  ..., 0.8078, 0.1195, 0.7176],
          [0.6494, 0.6220, 0.2252,  ..., 0.7480, 0.0063, 0.1142]],
 
         [[0.5813, 0.4309, 0.3536,  ..., 0.5249, 0.2415, 0.3704],
          [0.4365, 0.2039, 0.7007,  ..., 0.3696, 0.6232, 0.0524],
          [0.6360, 0.1025, 0.9094,  ..., 0.6889, 0.5269, 0.7484],
          ...,
          [0.1866, 0.8539, 0.2419,  ..., 0.9267, 0.4852, 0.6821],
          [0.7672, 0.6736, 0.8816,  ..., 0.6142, 0.9788, 0.0294],
          [0.1677, 0.7742, 0.6026,  ..., 0.6409, 0.6449, 0.8831]],
 
         [[0.6433, 0.0986, 0.3842,  ..., 0.4020, 0.1697, 0.9137],
          [0.7781, 0.4081, 0.5327,  ..., 0.5408, 0.7002, 0.1694],
          [0.6582, 0.6622, 0.7871,  ...,

In [92]:
x_original[0, 0, 0] = -5
x_original[0, 0, 0], x_permuted[0, 0, 0] # permuted returns a view

(tensor(-5.), tensor(-5.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [93]:
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
x = x.reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [95]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [96]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [97]:
x[0][0][0], x[0, 0, 0]

(tensor(1), tensor(1))

In [98]:
x[:, 0]

tensor([[1, 2, 3]])

In [99]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [100]:
x[:, 1, 1], x[0, 1, 1]

(tensor([5]), tensor(5))

In [101]:
x[0, 0, :], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [102]:
x[0, 2, 2], x[0][2][2]

(tensor(9), tensor(9))

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [103]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [104]:
# default numpy datatype is float64
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [105]:
# default torch datatype is float32
torch.arange(1.0, 8.0).dtype

torch.float32

In [106]:
# change data type
tensor_32 = tensor.type(torch.float32)
tensor_32.dtype, tensor.dtype

(torch.float32, torch.float64)

In [107]:
# Change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [108]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [109]:
# Change the tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short  how a neural netrwork learns:  
`start with a random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neaural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [110]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8992, 0.2988, 0.0824, 0.5927],
        [0.4190, 0.1783, 0.7755, 0.6153],
        [0.3736, 0.3605, 0.0034, 0.1829]])
tensor([[0.9123, 0.3912, 0.8135, 0.3079],
        [0.9918, 0.7363, 0.4408, 0.0878],
        [0.8750, 0.5242, 0.9563, 0.4381]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [111]:
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster comutations)

GPUs = faster computation on numbers, thanks to CUDA + NIVIDA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options... [see this post for what option to get](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/)
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to [PyTorch setup documentation](https://pytorch.org/get-started/locally/).


In [112]:
!nvidia-smi

Sat Oct  8 18:19:59 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Check for GPU access with PyTorch

In [113]:
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g run on GPU if available, else default to CPU

In [114]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device  

'cuda'

In [115]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on teh GPU is because using a GPU results in faster computations.

In [116]:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [117]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [119]:
# If tensor is on GPU, can't transform it to NumPy
#tensor_on_gpu.numpy()

In [120]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])

In [121]:
tensor_back_on_cpu.numpy()

array([1, 2, 3])

## Exercises & Extra-curiculum

[See exercises for this notebook here](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)